---
- hosts: all
  tasks:
    - name: install common tools
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - bind-utils
        - net-tools
        - vim
        - wget
        - epel-release
        - nginx-1.12.2-2.el7
      become: true

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: true

    - name: copying index file in the new server
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
      become: true

    - name: Start service nginx, if not started and enable it
      service:
        name: nginx
        state: started
      become: true
